// Phase 9.7g: emoji catalogue for the composer picker.
//
// Hand-curated rather than pulled from a full Unicode dataset: the complete
// set is ~1,900 emoji and several hundred KB of names/keywords, which would
// dominate the bundle for a chat app where a few hundred cover essentially
// all real use. Everything here is widely supported across platforms, so we
// avoid the tofu boxes that newer additions still produce on older systems.
//
// Skin-tone variants are deliberately omitted -- they multiply the list by
// six for a feature nobody has asked for yet. Adding them later means a
// modifier row in the picker, not a change to this shape.
//
// `k` (keywords) exists so search finds things by intent rather than by the
// official Unicode name: "lol" should find 😂, whose actual name is "face
// with tears of joy".

export interface Emoji {
  c: string;
  n: string;
  k: string[];
}

export interface EmojiCategory {
  id: string;
  label: string;
  emoji: Emoji[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "smileys",
    label: "smileys",
    emoji: [
      { c: "😀", n: "grinning", k: ["smile", "happy"] },
      { c: "😃", n: "smiley", k: ["happy", "joy"] },
      { c: "😄", n: "smile", k: ["happy", "laugh"] },
      { c: "😁", n: "grin", k: ["happy"] },
      { c: "😆", n: "laughing", k: ["lol", "haha"] },
      { c: "😅", n: "sweat smile", k: ["relief", "phew"] },
      { c: "🤣", n: "rofl", k: ["lol", "rolling", "laugh"] },
      { c: "😂", n: "joy", k: ["lol", "cry", "laugh", "tears"] },
      { c: "🙂", n: "slight smile", k: ["happy"] },
      { c: "🙃", n: "upside down", k: ["sarcasm", "irony"] },
      { c: "😉", n: "wink", k: ["flirt"] },
      { c: "😊", n: "blush", k: ["happy", "shy"] },
      { c: "😇", n: "innocent", k: ["angel", "halo"] },
      { c: "😍", n: "heart eyes", k: ["love", "crush"] },
      { c: "🤩", n: "star struck", k: ["wow", "amazed"] },
      { c: "😘", n: "kissing heart", k: ["kiss", "love"] },
      { c: "😗", n: "kissing", k: ["kiss"] },
      { c: "😋", n: "yum", k: ["tongue", "tasty"] },
      { c: "😛", n: "tongue out", k: ["cheeky"] },
      { c: "😜", n: "wink tongue", k: ["cheeky", "joke"] },
      { c: "🤪", n: "zany", k: ["crazy", "silly"] },
      { c: "🤨", n: "raised eyebrow", k: ["skeptical", "suspicious"] },
      { c: "🧐", n: "monocle", k: ["inspect", "scrutiny"] },
      { c: "🤓", n: "nerd", k: ["glasses", "geek"] },
      { c: "😎", n: "sunglasses", k: ["cool"] },
      { c: "🥳", n: "partying", k: ["celebrate", "birthday"] },
      { c: "😏", n: "smirk", k: ["smug"] },
      { c: "😒", n: "unamused", k: ["meh", "annoyed"] },
      { c: "😞", n: "disappointed", k: ["sad"] },
      { c: "😔", n: "pensive", k: ["sad", "thoughtful"] },
      { c: "😟", n: "worried", k: ["concern"] },
      { c: "🙁", n: "slight frown", k: ["sad"] },
      { c: "😣", n: "persevere", k: ["struggle"] },
      { c: "😖", n: "confounded", k: ["frustrated"] },
      { c: "😫", n: "tired", k: ["exhausted"] },
      { c: "😩", n: "weary", k: ["tired", "ugh"] },
      { c: "🥺", n: "pleading", k: ["puppy eyes", "please"] },
      { c: "😢", n: "cry", k: ["sad", "tear"] },
      { c: "😭", n: "sob", k: ["cry", "bawling"] },
      { c: "😤", n: "triumph", k: ["huff", "determined"] },
      { c: "😠", n: "angry", k: ["mad"] },
      { c: "😡", n: "rage", k: ["furious", "mad"] },
      { c: "🤬", n: "cursing", k: ["swearing", "angry"] },
      { c: "🤯", n: "mind blown", k: ["explode", "shock"] },
      { c: "😳", n: "flushed", k: ["embarrassed", "shock"] },
      { c: "🥵", n: "hot", k: ["heat", "sweating"] },
      { c: "🥶", n: "cold", k: ["freezing"] },
      { c: "😱", n: "scream", k: ["fear", "shock"] },
      { c: "😨", n: "fearful", k: ["scared"] },
      { c: "😰", n: "anxious", k: ["nervous", "sweat"] },
      { c: "😥", n: "sad relieved", k: ["phew", "sad"] },
      { c: "😓", n: "downcast sweat", k: ["tired", "sad"] },
      { c: "🤗", n: "hugging", k: ["hug"] },
      { c: "🤔", n: "thinking", k: ["hmm", "consider"] },
      { c: "🤭", n: "hand over mouth", k: ["oops", "giggle"] },
      { c: "🤫", n: "shushing", k: ["quiet", "secret"] },
      { c: "🤥", n: "lying", k: ["pinocchio", "liar"] },
      { c: "😶", n: "no mouth", k: ["speechless", "silence"] },
      { c: "😐", n: "neutral", k: ["meh", "blank"] },
      { c: "😑", n: "expressionless", k: ["blank"] },
      { c: "😬", n: "grimace", k: ["awkward", "yikes"] },
      { c: "🙄", n: "eye roll", k: ["annoyed", "whatever"] },
      { c: "😯", n: "hushed", k: ["surprised"] },
      { c: "😴", n: "sleeping", k: ["zzz", "tired"] },
      { c: "🤤", n: "drooling", k: ["hungry"] },
      { c: "😪", n: "sleepy", k: ["tired"] },
      { c: "😵", n: "dizzy", k: ["knocked out"] },
      { c: "🤐", n: "zipper mouth", k: ["quiet", "secret"] },
      { c: "🤢", n: "nauseated", k: ["sick", "gross"] },
      { c: "🤮", n: "vomiting", k: ["sick", "puke"] },
      { c: "🤧", n: "sneezing", k: ["sick", "tissue"] },
      { c: "😷", n: "mask", k: ["sick", "ill"] },
      { c: "🤒", n: "thermometer", k: ["sick", "fever"] },
      { c: "🤕", n: "bandage", k: ["hurt", "injured"] },
      { c: "🥴", n: "woozy", k: ["drunk", "dazed"] },
      { c: "😈", n: "devil", k: ["evil", "mischief"] },
      { c: "💀", n: "skull", k: ["dead", "death"] },
      { c: "☠️", n: "skull crossbones", k: ["danger", "poison"] },
      { c: "👻", n: "ghost", k: ["halloween", "boo"] },
      { c: "👽", n: "alien", k: ["ufo", "space"] },
      { c: "🤖", n: "robot", k: ["bot", "ai"] },
      { c: "💩", n: "poop", k: ["crap", "shit"] },
      { c: "🤡", n: "clown", k: ["joker"] },
    ],
  },
  {
    id: "gestures",
    label: "people",
    emoji: [
      { c: "👍", n: "thumbs up", k: ["yes", "approve", "ok", "+1"] },
      { c: "👎", n: "thumbs down", k: ["no", "disapprove", "-1"] },
      { c: "👌", n: "ok hand", k: ["perfect", "fine"] },
      { c: "🤌", n: "pinched fingers", k: ["italian"] },
      { c: "✌️", n: "victory", k: ["peace"] },
      { c: "🤞", n: "crossed fingers", k: ["luck", "hope"] },
      { c: "🤟", n: "love you", k: ["ily"] },
      { c: "🤘", n: "rock on", k: ["horns", "metal"] },
      { c: "🤙", n: "call me", k: ["shaka", "hang loose"] },
      { c: "👈", n: "point left", k: ["direction"] },
      { c: "👉", n: "point right", k: ["direction", "this"] },
      { c: "👆", n: "point up", k: ["above", "this"] },
      { c: "👇", n: "point down", k: ["below"] },
      { c: "☝️", n: "index up", k: ["one", "attention"] },
      { c: "✋", n: "raised hand", k: ["stop", "high five"] },
      { c: "🖐️", n: "hand splayed", k: ["five", "stop"] },
      { c: "🖖", n: "vulcan", k: ["spock", "star trek"] },
      { c: "👋", n: "wave", k: ["hello", "bye", "hi"] },
      { c: "🤝", n: "handshake", k: ["deal", "agree"] },
      { c: "🙏", n: "pray", k: ["thanks", "please", "namaste"] },
      { c: "✍️", n: "writing", k: ["write", "note"] },
      { c: "💪", n: "muscle", k: ["strong", "flex", "gym"] },
      { c: "🦾", n: "mechanical arm", k: ["prosthetic", "robot"] },
      { c: "🧠", n: "brain", k: ["smart", "think"] },
      { c: "👀", n: "eyes", k: ["look", "watch", "see"] },
      { c: "👏", n: "clap", k: ["applause", "bravo"] },
      { c: "🙌", n: "raised hands", k: ["celebrate", "praise", "hooray"] },
      { c: "🤲", n: "palms up", k: ["offer", "pray"] },
      { c: "🤦", n: "facepalm", k: ["disbelief", "smh"] },
      { c: "🤷", n: "shrug", k: ["dunno", "idk", "whatever"] },
      { c: "🙇", n: "bow", k: ["sorry", "respect"] },
      { c: "💁", n: "info desk", k: ["sassy", "tipping hand"] },
      { c: "🙋", n: "raising hand", k: ["question", "me", "here"] },
      { c: "🧑‍💻", n: "technologist", k: ["coder", "developer", "programmer"] },
      { c: "👨‍💻", n: "man technologist", k: ["coder", "developer"] },
      { c: "👩‍💻", n: "woman technologist", k: ["coder", "developer"] },
      { c: "🕵️", n: "detective", k: ["spy", "investigate"] },
      { c: "💃", n: "dancer", k: ["dance", "party"] },
      { c: "🕺", n: "man dancing", k: ["dance", "disco"] },
      { c: "👶", n: "baby", k: ["infant"] },
      { c: "🧙", n: "mage", k: ["wizard", "magic"] },
      { c: "🦸", n: "superhero", k: ["hero"] },
      { c: "🥷", n: "ninja", k: ["stealth"] },
      { c: "🤠", n: "cowboy", k: ["hat", "yeehaw"] },
    ],
  },
  {
    id: "nature",
    label: "nature",
    emoji: [
      { c: "🐶", n: "dog", k: ["puppy", "pet"] },
      { c: "🐱", n: "cat", k: ["kitten", "pet"] },
      { c: "🐭", n: "mouse", k: ["rodent"] },
      { c: "🐹", n: "hamster", k: ["pet"] },
      { c: "🐰", n: "rabbit", k: ["bunny"] },
      { c: "🦊", n: "fox", k: ["animal"] },
      { c: "🐻", n: "bear", k: ["animal"] },
      { c: "🐼", n: "panda", k: ["bear"] },
      { c: "🐨", n: "koala", k: ["australia"] },
      { c: "🐯", n: "tiger", k: ["big cat"] },
      { c: "🦁", n: "lion", k: ["king"] },
      { c: "🐮", n: "cow", k: ["moo"] },
      { c: "🐷", n: "pig", k: ["oink"] },
      { c: "🐵", n: "monkey", k: ["ape"] },
      { c: "🙈", n: "see no evil", k: ["monkey", "hide"] },
      { c: "🙉", n: "hear no evil", k: ["monkey"] },
      { c: "🙊", n: "speak no evil", k: ["monkey", "quiet"] },
      { c: "🐔", n: "chicken", k: ["hen"] },
      { c: "🐧", n: "penguin", k: ["linux", "bird"] },
      { c: "🐦", n: "bird", k: ["tweet"] },
      { c: "🦆", n: "duck", k: ["quack"] },
      { c: "🦉", n: "owl", k: ["wise", "night"] },
      { c: "🐝", n: "bee", k: ["honey", "buzz"] },
      { c: "🐛", n: "bug", k: ["caterpillar", "insect"] },
      { c: "🦋", n: "butterfly", k: ["insect"] },
      { c: "🐌", n: "snail", k: ["slow"] },
      { c: "🐞", n: "lady beetle", k: ["bug", "ladybug"] },
      { c: "🕷️", n: "spider", k: ["web", "insect"] },
      { c: "🐢", n: "turtle", k: ["slow", "tortoise"] },
      { c: "🐍", n: "snake", k: ["python", "serpent"] },
      { c: "🦖", n: "t-rex", k: ["dinosaur"] },
      { c: "🐙", n: "octopus", k: ["tentacles"] },
      { c: "🐳", n: "whale", k: ["ocean", "docker"] },
      { c: "🐬", n: "dolphin", k: ["ocean"] },
      { c: "🐟", n: "fish", k: ["ocean"] },
      { c: "🦈", n: "shark", k: ["ocean", "jaws"] },
      { c: "🌵", n: "cactus", k: ["desert", "plant"] },
      { c: "🌲", n: "evergreen", k: ["tree", "forest"] },
      { c: "🌳", n: "tree", k: ["forest"] },
      { c: "🌴", n: "palm tree", k: ["tropical", "beach"] },
      { c: "🌱", n: "seedling", k: ["plant", "sprout", "growth"] },
      { c: "🍀", n: "four leaf clover", k: ["luck", "lucky"] },
      { c: "🌿", n: "herb", k: ["leaf", "plant"] },
      { c: "🍁", n: "maple leaf", k: ["canada", "autumn"] },
      { c: "🌷", n: "tulip", k: ["flower"] },
      { c: "🌹", n: "rose", k: ["flower", "love"] },
      { c: "🌻", n: "sunflower", k: ["flower"] },
      { c: "🌸", n: "cherry blossom", k: ["flower", "sakura"] },
      { c: "🌎", n: "earth", k: ["world", "globe", "planet"] },
      { c: "🌙", n: "crescent moon", k: ["night"] },
      { c: "⭐", n: "star", k: ["favourite"] },
      { c: "🌟", n: "glowing star", k: ["sparkle"] },
      { c: "✨", n: "sparkles", k: ["shiny", "magic", "clean"] },
      { c: "⚡", n: "lightning", k: ["zap", "fast", "power"] },
      { c: "🔥", n: "fire", k: ["lit", "hot", "flame"] },
      { c: "💥", n: "boom", k: ["explosion", "collision"] },
      { c: "❄️", n: "snowflake", k: ["cold", "winter"] },
      { c: "🌊", n: "wave", k: ["ocean", "water"] },
      { c: "☀️", n: "sun", k: ["sunny", "weather"] },
      { c: "☁️", n: "cloud", k: ["weather", "cloudy"] },
      { c: "🌈", n: "rainbow", k: ["pride", "colour"] },
      { c: "🌧️", n: "rain", k: ["weather", "wet"] },
    ],
  },
  {
    id: "food",
    label: "food",
    emoji: [
      { c: "🍎", n: "apple", k: ["fruit"] },
      { c: "🍌", n: "banana", k: ["fruit"] },
      { c: "🍇", n: "grapes", k: ["fruit", "wine"] },
      { c: "🍓", n: "strawberry", k: ["fruit", "berry"] },
      { c: "🍑", n: "peach", k: ["fruit"] },
      { c: "🍊", n: "orange", k: ["fruit", "citrus"] },
      { c: "🍋", n: "lemon", k: ["citrus", "sour"] },
      { c: "🍉", n: "watermelon", k: ["fruit", "summer"] },
      { c: "🥑", n: "avocado", k: ["toast", "guacamole"] },
      { c: "🍅", n: "tomato", k: ["vegetable"] },
      { c: "🌽", n: "corn", k: ["maize"] },
      { c: "🥕", n: "carrot", k: ["vegetable"] },
      { c: "🥔", n: "potato", k: ["vegetable"] },
      { c: "🍞", n: "bread", k: ["loaf", "toast"] },
      { c: "🥐", n: "croissant", k: ["french", "pastry"] },
      { c: "🧀", n: "cheese", k: ["dairy"] },
      { c: "🥚", n: "egg", k: ["breakfast"] },
      { c: "🥓", n: "bacon", k: ["breakfast", "pork"] },
      { c: "🍔", n: "hamburger", k: ["burger", "fast food"] },
      { c: "🍟", n: "fries", k: ["chips", "fast food"] },
      { c: "🍕", n: "pizza", k: ["slice", "italian"] },
      { c: "🌭", n: "hot dog", k: ["sausage"] },
      { c: "🌮", n: "taco", k: ["mexican"] },
      { c: "🌯", n: "burrito", k: ["mexican", "wrap"] },
      { c: "🥗", n: "salad", k: ["healthy", "greens"] },
      { c: "🍝", n: "spaghetti", k: ["pasta", "italian"] },
      { c: "🍜", n: "ramen", k: ["noodles", "soup"] },
      { c: "🍣", n: "sushi", k: ["japanese", "fish"] },
      { c: "🍤", n: "fried shrimp", k: ["tempura", "seafood"] },
      { c: "🍚", n: "rice", k: ["bowl"] },
      { c: "🥟", n: "dumpling", k: ["gyoza", "potsticker"] },
      { c: "🍿", n: "popcorn", k: ["movie", "snack"] },
      { c: "🧂", n: "salt", k: ["salty", "seasoning"] },
      { c: "🍩", n: "doughnut", k: ["donut", "sweet"] },
      { c: "🍪", n: "cookie", k: ["biscuit", "sweet"] },
      { c: "🎂", n: "birthday cake", k: ["celebrate", "party"] },
      { c: "🍰", n: "cake", k: ["slice", "dessert"] },
      { c: "🍫", n: "chocolate", k: ["sweet", "candy"] },
      { c: "🍬", n: "candy", k: ["sweet"] },
      { c: "🍦", n: "ice cream", k: ["dessert", "soft serve"] },
      { c: "☕", n: "coffee", k: ["cafe", "hot", "espresso"] },
      { c: "🍵", n: "tea", k: ["green tea", "hot"] },
      { c: "🧃", n: "juice box", k: ["drink"] },
      { c: "🥤", n: "cup with straw", k: ["soda", "drink"] },
      { c: "🍺", n: "beer", k: ["pint", "drink", "pub"] },
      { c: "🍻", n: "cheers", k: ["beers", "toast"] },
      { c: "🍷", n: "wine", k: ["glass", "drink"] },
      { c: "🥂", n: "champagne", k: ["toast", "celebrate"] },
      { c: "🥃", n: "whisky", k: ["tumbler", "drink"] },
      { c: "🍾", n: "bottle pop", k: ["champagne", "celebrate"] },
    ],
  },
  {
    id: "activity",
    label: "activity",
    emoji: [
      { c: "⚽", n: "soccer", k: ["football", "sport"] },
      { c: "🏀", n: "basketball", k: ["sport"] },
      { c: "🏈", n: "american football", k: ["sport", "nfl"] },
      { c: "⚾", n: "baseball", k: ["sport"] },
      { c: "🎾", n: "tennis", k: ["sport"] },
      { c: "🏐", n: "volleyball", k: ["sport"] },
      { c: "🏓", n: "ping pong", k: ["table tennis", "sport"] },
      { c: "🏸", n: "badminton", k: ["sport"] },
      { c: "🥅", n: "goal", k: ["net", "sport"] },
      { c: "🏆", n: "trophy", k: ["win", "champion", "award"] },
      { c: "🥇", n: "gold medal", k: ["first", "win"] },
      { c: "🥈", n: "silver medal", k: ["second"] },
      { c: "🥉", n: "bronze medal", k: ["third"] },
      { c: "🎯", n: "bullseye", k: ["target", "dart", "goal"] },
      { c: "🎮", n: "video game", k: ["gaming", "controller"] },
      { c: "🕹️", n: "joystick", k: ["arcade", "gaming"] },
      { c: "🎲", n: "dice", k: ["random", "game", "luck"] },
      { c: "♟️", n: "chess pawn", k: ["chess", "strategy"] },
      { c: "🧩", n: "puzzle", k: ["jigsaw", "piece"] },
      { c: "🎸", n: "guitar", k: ["music", "rock"] },
      { c: "🎹", n: "keyboard", k: ["piano", "music"] },
      { c: "🥁", n: "drum", k: ["music", "beat"] },
      { c: "🎧", n: "headphones", k: ["music", "listen"] },
      { c: "🎤", n: "microphone", k: ["sing", "karaoke"] },
      { c: "🎬", n: "clapper", k: ["movie", "film", "action"] },
      { c: "🎨", n: "art", k: ["palette", "paint", "design"] },
      { c: "🚴", n: "cycling", k: ["bike", "sport"] },
      { c: "🏃", n: "running", k: ["run", "sport"] },
      { c: "🏊", n: "swimming", k: ["swim", "sport"] },
      { c: "🧘", n: "yoga", k: ["meditate", "calm"] },
      { c: "🎉", n: "party popper", k: ["celebrate", "tada", "congrats"] },
      { c: "🎊", n: "confetti", k: ["celebrate", "party"] },
      { c: "🎁", n: "gift", k: ["present", "birthday"] },
    ],
  },
  {
    id: "travel",
    label: "travel",
    emoji: [
      { c: "🚗", n: "car", k: ["drive", "auto"] },
      { c: "🚕", n: "taxi", k: ["cab"] },
      { c: "🚙", n: "suv", k: ["car"] },
      { c: "🚌", n: "bus", k: ["transport"] },
      { c: "🏎️", n: "race car", k: ["f1", "fast"] },
      { c: "🚓", n: "police car", k: ["cop"] },
      { c: "🚑", n: "ambulance", k: ["emergency"] },
      { c: "🚒", n: "fire engine", k: ["emergency"] },
      { c: "🚚", n: "truck", k: ["delivery", "lorry"] },
      { c: "🚜", n: "tractor", k: ["farm"] },
      { c: "🛵", n: "scooter", k: ["moped"] },
      { c: "🏍️", n: "motorcycle", k: ["bike"] },
      { c: "🚲", n: "bicycle", k: ["bike", "cycle"] },
      { c: "✈️", n: "airplane", k: ["flight", "travel", "fly"] },
      { c: "🚀", n: "rocket", k: ["launch", "ship it", "space"] },
      { c: "🛸", n: "ufo", k: ["alien", "flying saucer"] },
      { c: "🚁", n: "helicopter", k: ["chopper"] },
      { c: "⛵", n: "sailboat", k: ["boat", "sail"] },
      { c: "🚢", n: "ship", k: ["cruise", "boat"] },
      { c: "🚂", n: "train", k: ["locomotive", "rail"] },
      { c: "🚇", n: "metro", k: ["subway", "underground"] },
      { c: "🗺️", n: "map", k: ["world", "travel"] },
      { c: "🏔️", n: "mountain", k: ["snow", "peak"] },
      { c: "🏕️", n: "camping", k: ["tent", "outdoors"] },
      { c: "🏖️", n: "beach", k: ["holiday", "sand"] },
      { c: "🏝️", n: "island", k: ["tropical", "desert island"] },
      { c: "🏠", n: "house", k: ["home"] },
      { c: "🏢", n: "office", k: ["building", "work"] },
      { c: "🏥", n: "hospital", k: ["medical"] },
      { c: "🏰", n: "castle", k: ["fortress"] },
      { c: "🗼", n: "tower", k: ["tokyo", "landmark"] },
      { c: "🗽", n: "statue of liberty", k: ["new york", "usa"] },
      { c: "🌉", n: "bridge", k: ["night", "city"] },
      { c: "🌃", n: "night city", k: ["skyline", "stars"] },
    ],
  },
  {
    id: "objects",
    label: "objects",
    emoji: [
      { c: "💻", n: "laptop", k: ["computer", "code", "work"] },
      { c: "🖥️", n: "desktop", k: ["computer", "monitor"] },
      { c: "⌨️", n: "keyboard", k: ["type", "input"] },
      { c: "🖱️", n: "mouse", k: ["click", "computer"] },
      { c: "🖨️", n: "printer", k: ["print", "paper"] },
      { c: "💾", n: "floppy disk", k: ["save", "retro"] },
      { c: "💿", n: "disc", k: ["cd", "dvd"] },
      { c: "📀", n: "dvd", k: ["disc"] },
      { c: "📱", n: "phone", k: ["mobile", "smartphone"] },
      { c: "☎️", n: "telephone", k: ["call", "landline"] },
      { c: "📞", n: "receiver", k: ["call", "phone"] },
      { c: "📷", n: "camera", k: ["photo", "picture"] },
      { c: "📹", n: "video camera", k: ["record", "film"] },
      { c: "🔋", n: "battery", k: ["power", "charge"] },
      { c: "🔌", n: "plug", k: ["power", "electric"] },
      { c: "💡", n: "bulb", k: ["idea", "light"] },
      { c: "🔦", n: "flashlight", k: ["torch", "light"] },
      { c: "🕯️", n: "candle", k: ["light", "flame"] },
      { c: "🔍", n: "magnifying glass", k: ["search", "find", "zoom"] },
      { c: "🔒", n: "lock", k: ["secure", "private", "encrypted"] },
      { c: "🔓", n: "unlock", k: ["open", "insecure"] },
      { c: "🔑", n: "key", k: ["password", "access"] },
      { c: "🔨", n: "hammer", k: ["tool", "build"] },
      { c: "🔧", n: "wrench", k: ["tool", "fix", "config"] },
      { c: "🪛", n: "screwdriver", k: ["tool", "fix"] },
      { c: "⚙️", n: "gear", k: ["settings", "config", "cog"] },
      { c: "🧰", n: "toolbox", k: ["tools", "repair"] },
      { c: "🧲", n: "magnet", k: ["attract"] },
      { c: "🧪", n: "test tube", k: ["science", "experiment", "lab"] },
      { c: "🔬", n: "microscope", k: ["science", "research"] },
      { c: "🛰️", n: "satellite", k: ["space", "orbit"] },
      { c: "📡", n: "satellite dish", k: ["signal", "antenna"] },
      { c: "📦", n: "package", k: ["box", "delivery", "shipping"] },
      { c: "📬", n: "mailbox", k: ["mail", "post"] },
      { c: "✉️", n: "envelope", k: ["mail", "email", "letter"] },
      { c: "📝", n: "memo", k: ["note", "write", "edit"] },
      { c: "📅", n: "calendar", k: ["date", "schedule"] },
      { c: "📊", n: "bar chart", k: ["graph", "stats", "data"] },
      { c: "📈", n: "chart up", k: ["growth", "increase", "trend"] },
      { c: "📉", n: "chart down", k: ["decrease", "loss"] },
      { c: "📌", n: "pin", k: ["pinned", "location"] },
      { c: "📎", n: "paperclip", k: ["attach", "attachment"] },
      { c: "✂️", n: "scissors", k: ["cut"] },
      { c: "🗑️", n: "trash", k: ["delete", "bin", "garbage"] },
      { c: "🛒", n: "cart", k: ["shopping", "buy"] },
      { c: "💰", n: "money bag", k: ["cash", "rich"] },
      { c: "💳", n: "credit card", k: ["pay", "money"] },
      { c: "⌛", n: "hourglass", k: ["time", "wait", "loading"] },
      { c: "⏰", n: "alarm clock", k: ["time", "wake"] },
      { c: "🧨", n: "firecracker", k: ["dynamite", "explosive"] },
      { c: "🎈", n: "balloon", k: ["party", "celebrate"] },
      { c: "🧸", n: "teddy bear", k: ["toy", "plush"] },
      { c: "📚", n: "books", k: ["read", "study", "library"] },
      { c: "🏷️", n: "label", k: ["tag", "price"] },
    ],
  },
  {
    id: "symbols",
    label: "symbols",
    emoji: [
      { c: "❤️", n: "red heart", k: ["love", "like"] },
      { c: "🧡", n: "orange heart", k: ["love"] },
      { c: "💛", n: "yellow heart", k: ["love"] },
      { c: "💚", n: "green heart", k: ["love"] },
      { c: "💙", n: "blue heart", k: ["love"] },
      { c: "💜", n: "purple heart", k: ["love"] },
      { c: "🖤", n: "black heart", k: ["love", "dark"] },
      { c: "🤍", n: "white heart", k: ["love"] },
      { c: "💔", n: "broken heart", k: ["sad", "heartbreak"] },
      { c: "💕", n: "two hearts", k: ["love"] },
      { c: "💯", n: "hundred", k: ["100", "perfect", "score"] },
      { c: "✅", n: "check mark", k: ["done", "yes", "tick", "ok"] },
      { c: "☑️", n: "checkbox", k: ["done", "checked"] },
      { c: "❌", n: "cross mark", k: ["no", "wrong", "fail", "x"] },
      { c: "⛔", n: "no entry", k: ["forbidden", "stop"] },
      { c: "🚫", n: "prohibited", k: ["no", "ban"] },
      { c: "⚠️", n: "warning", k: ["caution", "alert"] },
      { c: "❗", n: "exclamation", k: ["important", "alert"] },
      { c: "❓", n: "question", k: ["help", "what"] },
      { c: "💬", n: "speech balloon", k: ["chat", "comment", "message"] },
      { c: "💭", n: "thought balloon", k: ["think", "dream"] },
      { c: "🔔", n: "bell", k: ["notification", "alert"] },
      { c: "🔕", n: "mute bell", k: ["silent", "no notifications"] },
      { c: "🔊", n: "speaker loud", k: ["volume", "sound"] },
      { c: "🔇", n: "mute", k: ["silent", "no sound"] },
      { c: "♻️", n: "recycle", k: ["reuse", "green"] },
      { c: "🔗", n: "link", k: ["url", "chain"] },
      { c: "🔄", n: "refresh", k: ["reload", "sync", "retry"] },
      { c: "▶️", n: "play", k: ["start", "run"] },
      { c: "⏸️", n: "pause", k: ["hold"] },
      { c: "⏹️", n: "stop", k: ["halt"] },
      { c: "⏩", n: "fast forward", k: ["skip", "speed"] },
      { c: "🔺", n: "red triangle up", k: ["increase"] },
      { c: "🔻", n: "red triangle down", k: ["decrease"] },
      { c: "⭕", n: "hollow circle", k: ["o", "correct"] },
      { c: "🆗", n: "ok button", k: ["okay", "agree"] },
      { c: "🆕", n: "new", k: ["fresh"] },
      { c: "🔥", n: "fire", k: ["lit", "hot"] },
      { c: "⚫", n: "black circle", k: ["dot"] },
      { c: "⚪", n: "white circle", k: ["dot"] },
      { c: "🟢", n: "green circle", k: ["online", "ok", "go"] },
      { c: "🟡", n: "yellow circle", k: ["away", "warning"] },
      { c: "🔴", n: "red circle", k: ["offline", "record", "stop"] },
      { c: "🔵", n: "blue circle", k: ["dot"] },
      { c: "🟣", n: "purple circle", k: ["dot"] },
      { c: "©️", n: "copyright", k: ["legal"] },
      { c: "™️", n: "trademark", k: ["legal", "brand"] },
      { c: "🔞", n: "eighteen plus", k: ["adult", "nsfw"] },
      { c: "〽️", n: "part alternation", k: ["mark"] },
      { c: "🈵", n: "no vacancy", k: ["full", "japanese"] },
    ],
  },
];

// Flattened view, built once at module load. Used by search and by any
// caller that wants "all emoji" without caring about grouping.
export const ALL_EMOJI: Emoji[] = EMOJI_CATEGORIES.flatMap((c) => c.emoji);

// searchEmoji matches the query against the name and the keywords. Substring
// rather than prefix so "smile" finds "sweat smile", and results are ranked
// so exact and prefix name matches float above incidental keyword hits --
// otherwise typing "cat" surfaces every animal before the cat itself.
export function searchEmoji(query: string, limit = 120): Emoji[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const scored: { e: Emoji; score: number }[] = [];
  for (const e of ALL_EMOJI) {
    let score = -1;
    if (e.n === q) score = 0;
    else if (e.n.startsWith(q)) score = 1;
    else if (e.k.some((k) => k === q)) score = 2;
    else if (e.n.includes(q)) score = 3;
    else if (e.k.some((k) => k.startsWith(q))) score = 4;
    else if (e.k.some((k) => k.includes(q))) score = 5;
    if (score >= 0) scored.push({ e, score });
  }
  scored.sort((a, b) => a.score - b.score);
  return scored.slice(0, limit).map((s) => s.e);
}

// insertAtCursor splices `insert` into `value` at the given selection range,
// returning the new value and where the caret should land. Pure so the
// caret arithmetic is testable without a DOM -- getting this wrong is the
// classic emoji-picker bug (text appended at the end, caret jumping to 0).
export function insertAtCursor(
  value: string,
  insert: string,
  selectionStart: number,
  selectionEnd: number,
): { value: string; caret: number } {
  const len = value.length;
  // Clamp: a stale selection (element re-rendered since) must not throw or
  // silently truncate the draft.
  const start = Math.max(0, Math.min(selectionStart, len));
  const end = Math.max(start, Math.min(selectionEnd, len));
  const next = value.slice(0, start) + insert + value.slice(end);
  return { value: next, caret: start + insert.length };
}
