package auth

import (
	"context"
	"errors"
	"sync"
	"time"

	"github.com/go-webauthn/webauthn/webauthn"
	"github.com/google/uuid"
)

// CeremonyKind discriminates entries in the cache. Sub-step 3 only
// uses KindRegistration; KindLogin lands in sub-step 4.
type CeremonyKind int

const (
	KindRegistration CeremonyKind = iota + 1
	KindLogin
)

// CeremonyEntry is one in-flight WebAuthn ceremony. It carries enough
// state from the Begin call to complete the Finish call without
// trusting any of it from the client at finish time.
//
// The cache key is the WebAuthn challenge string (already a 32-byte
// random value generated by go-webauthn). Keying on the challenge
// means:
//   - SPA doesn't have to round-trip a separate ID (it has the
//     challenge from BeginRegistration's response anyway)
//   - The cache key is unforgeable: an attacker cannot guess another
//     user's pending registration challenge
//   - Lookup is one map access
//
// PendingUser carries the username/displayName/email the SPA submitted
// at begin time. Sub-step 3 uses these at finish time to populate the
// users row. If we trusted the SPA to resubmit them at finish, a
// race-then-swap attack could let a registrant create a user with a
// different username than the one whose passkey they just minted.
type CeremonyEntry struct {
	Kind        CeremonyKind
	Session     webauthn.SessionData
	PendingUser PendingUser
	ExpiresAt   time.Time
}

// PendingUser bundles the form fields the SPA submits at register/begin
// that we need to remember through to register/finish. None of these
// have been validated against the database yet — that happens at finish
// time inside the transaction (collision checks, etc).
type PendingUser struct {
	ID          uuid.UUID
	Username    string
	DisplayName string
	Email       string
}

// DefaultCeremonyTTL is the lifetime of a pending ceremony before it's
// pruned. WebAuthn ceremonies are interactive — the user clicks a
// button, the authenticator does its work, and the SPA POSTs back —
// and almost always complete within seconds. 5 minutes is a
// conservative ceiling.
const DefaultCeremonyTTL = 5 * time.Minute

// DefaultJanitorInterval is how often the janitor scans for expired
// entries. The cost of a scan is O(entries); for our scale (single-
// digit concurrent registrations) any value in 10s..1min is fine.
const DefaultJanitorInterval = 30 * time.Second

// CeremonyCache is a goroutine-safe, TTL-bounded cache of in-flight
// WebAuthn ceremonies. Keyed by challenge string.
//
// Concurrency: a single sync.RWMutex protects the map. The Get and
// Take operations also delete on success (one-shot ceremonies), so
// they take the write lock; Put always takes the write lock.
//
// Lifecycle: New constructs an empty cache; RunJanitor starts a
// background goroutine that periodically prunes expired entries.
// The janitor exits when its context is canceled. Callers wire
// this into the server's lifecycle context.
type CeremonyCache struct {
	mu      sync.RWMutex
	entries map[string]CeremonyEntry
	ttl     time.Duration
	now     func() time.Time // overridable for tests
}

// NewCeremonyCache returns an empty cache with the given TTL. Pass
// zero TTL to use DefaultCeremonyTTL.
func NewCeremonyCache(ttl time.Duration) *CeremonyCache {
	if ttl <= 0 {
		ttl = DefaultCeremonyTTL
	}
	return &CeremonyCache{
		entries: make(map[string]CeremonyEntry),
		ttl:     ttl,
		now:     time.Now,
	}
}

// Put stores entry under the challenge key. Overwrites any existing
// entry with the same challenge (in practice unique by construction
// — challenges are 32-byte cryptographic randoms from go-webauthn —
// but we don't rely on that). The entry's ExpiresAt is set from
// the cache's TTL relative to now.
func (c *CeremonyCache) Put(challenge string, entry CeremonyEntry) {
	if challenge == "" {
		return
	}
	c.mu.Lock()
	defer c.mu.Unlock()
	entry.ExpiresAt = c.now().Add(c.ttl)
	c.entries[challenge] = entry
}

// Take fetches and removes the entry for challenge. One-shot semantics:
// once consumed, the ceremony cannot be re-used. Returns
// (entry, ErrCeremonyExpired) if the entry exists but its TTL has
// passed, and (CeremonyEntry{}, ErrCeremonyNotFound) if no entry exists.
//
// Expired entries are removed on lookup; the janitor is for entries
// that are never looked up (abandoned ceremonies).
func (c *CeremonyCache) Take(challenge string) (CeremonyEntry, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	entry, ok := c.entries[challenge]
	if !ok {
		return CeremonyEntry{}, ErrCeremonyNotFound
	}
	delete(c.entries, challenge)
	if c.now().After(entry.ExpiresAt) {
		return CeremonyEntry{}, ErrCeremonyExpired
	}
	return entry, nil
}

// Len returns the current number of entries. Test-only.
func (c *CeremonyCache) Len() int {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return len(c.entries)
}

// Prune removes all expired entries. Returns the number removed.
// Called periodically by RunJanitor. Idempotent; safe to call
// from multiple goroutines but the janitor is the only intended
// caller.
func (c *CeremonyCache) Prune() int {
	c.mu.Lock()
	defer c.mu.Unlock()
	now := c.now()
	removed := 0
	for k, v := range c.entries {
		if now.After(v.ExpiresAt) {
			delete(c.entries, k)
			removed++
		}
	}
	return removed
}

// RunJanitor sweeps expired entries at interval until ctx is canceled.
// Pass zero interval to use DefaultJanitorInterval. Returns when ctx
// is done. Run in its own goroutine; the server's lifecycle context
// is the natural fit.
func (c *CeremonyCache) RunJanitor(ctx context.Context, interval time.Duration) {
	if interval <= 0 {
		interval = DefaultJanitorInterval
	}
	t := time.NewTicker(interval)
	defer t.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-t.C:
			_ = c.Prune()
		}
	}
}

// Errors. Distinguished so callers can return different HTTP statuses
// (404 for not found, 410 Gone for expired).
var (
	ErrCeremonyNotFound = errors.New("auth: ceremony not found")
	ErrCeremonyExpired  = errors.New("auth: ceremony expired")
)
