// chalk-web -- esbuild driver.
//
// Bundles src/index.tsx + theme.css into dist/. The bundle is tiny
// (Preact runtime + our code, < 30 KB) and lives at dist/app.js
// alongside the source-mapped css.
//
// Invoked from go generate via `npm run build`. Watch mode is for
// local development; production builds go through the Dockerfile's
// frontend stage.

import * as esbuild from "esbuild";
import { copyFileSync, mkdirSync, existsSync, statSync } from "node:fs";

const watch = process.argv.includes("--watch");
const dev = process.env.NODE_ENV !== "production";

const outdir = "dist";
mkdirSync(outdir, { recursive: true });

// Static assets that the embedded FS needs to serve. We don't bundle
// these; we just copy them so index.html can reference them with
// stable paths under /.
const staticAssets = ["index.html"];
for (const f of staticAssets) {
  if (existsSync(f)) {
    copyFileSync(f, `${outdir}/${f}`);
  }
}

const buildOpts = {
  entryPoints: ["src/index.tsx", "src/theme.css"],
  bundle: true,
  outdir,
  format: "esm",
  target: ["es2022"],
  jsx: "automatic",
  jsxImportSource: "preact",
  minify: !dev,
  sourcemap: dev ? "inline" : false,
  // We want stable filenames so index.html can reference them without
  // a manifest indirection. The runtime fetch happens at the HTML
  // level via <script src="/app.js">.
  entryNames: "[name]",
  // Phase 9.6d: enable code-splitting so dynamic-import() calls
  // produce separate chunk files. The initial index.js bundle drops
  // significantly (~25-30%) because AdminPanel, FriendsPanel,
  // InvitesPanel, and ProfilePanel only load when their UI is opened.
  // Each chunk uses a content-hashed filename for cache-busting.
  splitting: true,
  chunkNames: "chunks/[name]-[hash]",
  // Phase 11a: external Node built-ins for @wireapp/core-crypto.
  //
  // core-crypto is isomorphic and contains conditional dynamic imports
  // of Node-only modules (fs/promises etc) that only execute under
  // Node. esbuild can't see they're unreachable in the browser, so
  // we mark them external. At runtime in the browser, those import
  // expressions live in dead-code branches and never execute.
  external: [
    "fs", "fs/promises",
    "path",
    "crypto",
    "os",
    "stream",
    "util",
    "url",
    "module",
    // node:-prefixed aliases that newer code sometimes uses.
    "node:fs", "node:fs/promises",
    "node:path",
    "node:crypto",
    "node:os",
    "node:stream",
    "node:util",
    "node:url",
    "node:module",
  ],
  loader: {
    ".woff2": "file",
    ".woff": "file",
    ".ttf": "file",
    ".svg": "file",
    ".png": "file",
  },
  logLevel: "info",
};

if (watch) {
  const ctx = await esbuild.context(buildOpts);
  await ctx.watch();
  console.log("watching for changes...");
} else {
  await esbuild.build(buildOpts);
  console.log("build complete");
}

// Phase 11a fix2: copy core-crypto WASM into dist/chunks/.
//
// @wireapp/core-crypto's runtime bootstrap does:
//   new URL("core-crypto-ffi_bg.wasm", import.meta.url)
// to find the WASM binary. import.meta.url at runtime resolves to
// the lazy chunk's served URL (/chunks/corecrypto-XXX.js), so the
// URL becomes /chunks/core-crypto-ffi_bg.wasm. esbuild doesn't see
// this static-string -> URL pattern, so we must copy the .wasm
// ourselves with the expected filename.
function copyCoreCryptoWasm() {
  const src = "node_modules/@wireapp/core-crypto/src/autogenerated/core-crypto-ffi_bg.wasm";
  const dst = `${outdir}/chunks/core-crypto-ffi_bg.wasm`;
  if (!existsSync(src)) {
    console.warn(`core-crypto WASM not found at ${src}; skipping copy`);
    return;
  }
  mkdirSync(`${outdir}/chunks`, { recursive: true });
  copyFileSync(src, dst);
  const sz = statSync(dst).size;
  console.log(`copied core-crypto WASM (${(sz / 1024 / 1024).toFixed(2)} MB) -> ${dst}`);
}
copyCoreCryptoWasm();
